# Generated by Django 4.2.20 on 2025-05-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_thread_user'),
        ('accounts', '0004_alter_user_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_authors',
            field=models.ManyToManyField(blank=True, related_name='fans_of_author', to='books.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='users_who_liked', to='books.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='fovorite_topics',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='books.category'),
        ),
    ]
