# Generated by Django 4.2.20 on 2025-05-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_favorite_authors_user_favorite_books_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fovorite_topics',
            new_name='favorite_topics',
        ),
    ]
