# Generated by Django 4.2.20 on 2025-05-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecommendation',
            name='reasons',
            field=models.JSONField(default=list),
        ),
    ]
