services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=your_django_project.settings.production
      - SECRET_KEY=your-secret-key

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - frontend
