services:
  backend:
    build: ./backend
    environment:
      - DJANGO_SETTINGS_MODULE=mypjt.settings.production
      - SECRET_KEY=django-insecure-8ae=1thie9jmq8y#%kfv16q$r37wm=uqj-ur1&e)b)z0!baltb

  frontend:
    build: ./frontend
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - frontend
