enversion: '3.8'
services:
  django:
    build:
      context: ./backend
    volumes:
      - static_volume:/app/static
    expose:
      - "8000"
    env_file:
      - ./backend/.env

  vue:
    build:
      context: ./frontend
    expose:
      - "80"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/backend/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
      - vue

volumes:
  static_volume: