version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=mypjt.settings
      - SECRET_KEY=django-insecure-8ae=1thie9jmq8y#%kfv16q$r37wm=uqj-ur1&e)b)z0!baltb
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn mypjt.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend

  nginx:
    build: ./nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - staticfiles:/app/staticfiles:ro
      - media:/app/media:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

volumes:
  staticfiles:
  media:
