version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - webnet

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    networks:
      - webnet
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

networks:
  webnet:
