# Generated by Django 4.2.20 on 2025-05-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_marketcomment_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketpost',
            name='status',
            field=models.CharField(choices=[('판매중', '판매중'), ('판매완료', '판매완료'), ('예악중', '예약중')], default='판매중', max_length=10),
        ),
    ]
