# Generated by Django 4.2.20 on 2025-05-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_alter_marketpost_status'),
        ('markets', '0004_marketpost_price_alter_marketpost_status'),
    ]

    operations = [
    ]
