# Generated by Django 4.2.20 on 2025-05-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_merge_20250527_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketpost',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
