# Generated by Django 4.2.20 on 2025-05-24 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_alter_category_name_alter_thread_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userthreads', to=settings.AUTH_USER_MODEL),
        ),
    ]
