# Generated by Django 4.2.20 on 2025-05-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_likes_bookrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.JSONField(default=list),
        ),
    ]
